### ISSUE TITLE
体适能不能用了

### ISSUE THREAD

**Issue by jmsya** [Envystar/BetterRunning#1]

**Comment by Envystar** [comment]
可以正常使用的

**Comment by jmsya** [comment]
> 可以正常使用的

不能修补体适能了

**Comment by Envystar** [comment]
能否给出具体的问题？

**Comment by jmsya** [comment]
版本更新不能修补了

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Envystar** [comment]
可能应用更新后有加固了，可以先脱壳再尝试，这个可以另找教程
